### ISSUE TITLE
Unrecognized option 'max_muxing_queue_size'. Error splitting the argument list: Option not found

### ISSUE THREAD

**Issue by ethanopp** [Collisionc/sickbeard_mp4_automator#10]
Just switched over from mdhiggins because I wanted to take advantage of your burn_in_forced_subs setting...

Getting the following error when the script gets called from sonarr:
```
2018-02-10 23:48:52 - SonarrPostConversion - INFO - Sonarr extra script post processing started.
2018-02-10 23:48:52 - readSettings - INFO - /usr/bin/python
2018-02-10 23:48:52 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
2018-02-10 23:48:52 - readSettings - WARNING - Sample rate was invalid, defaulting to 48000 KHz.
2018-02-10 23:48:52 - SonarrPostConversion - INFO - Processing /library/TV Shows/High Maintenance (2016)/Season 02/High Maintenance (2016) - S02E04 - Derech WEBDL-1080p.mkv.
2018-02-10 23:48:55 - mkvtomp4 - INFO - Reading video stream.
2018-02-10 23:48:55 - mkvtomp4 - INFO - Video codec detected: h264.
2018-02-10 23:48:55 - mkvtomp4 - INFO - Pix Fmt: yuv420p.
2018-02-10 23:48:55 - mkvtomp4 - INFO - Reading audio streams.
2018-02-10 23:48:55 - mkvtomp4 - INFO - Audio detected for stream #1: eac3 [eng].
2018-02-10 23:48:55 - mkvtomp4 - INFO - Creating audio stream 0 from source audio stream 1 [iOS-audio].
2018-02-10 23:48:55 - mkvtomp4 - INFO - Audio track is number 0 setting disposition to default
2018-02-10 23:48:55 - mkvtomp4 - INFO - Creating audio stream 1 from source stream 1.
2018-02-10 23:48:55 - mkvtomp4 - INFO - Audio Track is number 1 setting disposition to none
2018-02-10 23:48:55 - mkvtomp4 - INFO - Reading subtitle streams.
2018-02-10 23:48:55 - mkvtomp4 - INFO - Subtitle detected for stream #2: srt [eng].
2018-02-10 23:48:55 - mkvtomp4 - INFO - Couldn't use experimental forced subtitle duration.
2018-02-10 23:48:55 - mkvtomp4 - INFO - Subtitle detected for stream #3: srt [eng].
2018-02-10 23:48:55 - mkvtomp4 - INFO - Couldn't use experimental forced subtitle duration.
2018-02-10 23:48:55 - mkvtomp4 - INFO - Creating subtitle stream 0 from source stream 2.
2018-02-10 23:48:55 - mkvtomp4 - INFO - Creating subtitle stream 1 from source stream 3.
2018-02-10 23:48:55 - mkvtomp4 - INFO - Starting conversion.
2018-02-10 23:48:55 - mkvtomp4 - ERROR - Error converting file, FFMPEG error.
Traceback (most recent call last):
  File "/sickbeard_mp4_automator/mkvtomp4.py", line 966, in convert
    for timecode in conv:
  File "/sickbeard_mp4_automator/converter/__init__.py", line 243, in convert
    timeout=timeout, preopts=preopts, postopts=postopts):
  File "/sickbeard_mp4_automator/converter/ffmpeg.py", line 632, in convert
    total_output, pid=p.pid)
FFMpegConvertError: <FFMpegConvertError error="Exited with code 1", pid=317, cmd="/usr/bin/ffmpeg -fix_sub_duration -vsync -1 -i /library/TV Shows/High Maintenance (2016)/Season 02/High Maintenance (2016) - S02E04 - Derech WEBDL-1080p.mkv -vcodec copy -map 0:0 -c:a:0 aac -map 0:1 -disposition:a:0 default -ac:a:0 2 -b:a:0 256k -ar:a:0 48000 -metadata:s:a:0 language=eng -strict experimental -c:a:1 ac3 -map 0:1 -disposition:a:1 none -ac:a:1 6 -b:a:1 1536k -ar:a:1 48000 -metadata:s:a:1 language=eng -c:s:0 mov_text -map 0:2 -disposition:s:0 default -metadata:s:s:0 language=eng -c:s:1 mov_text -map 0:3 -disposition:s:1 default -metadata:s:s:1 language=eng -f mp4 -threads 0 -max_muxing_queue_size 2048 -movflags faststart -preset ultrafast -y /library/TV Shows/High Maintenance (2016)/Season 02/High Maintenance (2016) - S02E04 - Derech WEBDL-1080p.mp4">
2018-02-10 23:48:55 - mkvtomp4 - ERROR - /usr/bin/ffmpeg -fix_sub_duration -vsync -1 -i /library/TV Shows/High Maintenance (2016)/Season 02/High Maintenance (2016) - S02E04 - Derech WEBDL-1080p.mkv -vcodec copy -map 0:0 -c:a:0 aac -map 0:1 -disposition:a:0 default -ac:a:0 2 -b:a:0 256k -ar:a:0 48000 -metadata:s:a:0 language=eng -strict experimental -c:a:1 ac3 -map 0:1 -disposition:a:1 none -ac:a:1 6 -b:a:1 1536k -ar:a:1 48000 -metadata:s:a:1 language=eng -c:s:0 mov_text -map 0:2 -disposition:s:0 default -metadata:s:s:0 language=eng -c:s:1 mov_text -map 0:3 -disposition:s:1 default -metadata:s:s:1 language=eng -f mp4 -threads 0 -max_muxing_queue_size 2048 -movflags faststart -preset ultrafast -y /library/TV Shows/High Maintenance (2016)/Season 02/High Maintenance (2016) - S02E04 - Derech WEBDL-1080p.mp4
2018-02-10 23:48:55 - mkvtomp4 - ERROR - ffmpeg version 2.8.11-0ubuntu0.16.04.1 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Unrecognized option 'max_muxing_queue_size'.
Error splitting the argument list: Option not found
```

Here are my settings:
[MP4]
ffmpeg = ffmpeg
ffprobe = ffprobe
threads = auto
output_directory =
copy_to =
move_to =
output_extension = mp4
output_format = mp4
delete_original = True
relocate_moov = True
video-codec = h264,x264,h265,x265
video-bitrate =
resolution-bitrate-restriction =
video-crf =
video-max-width =
h264-max-level =
use-qsv-decoder-with-encoder = True
use-hevc-qsv-decoder = False
enable_dxva2_gpu_decode = False
ios-audio = True
qmin =
qmax = 
global_quality = 
maxrate =
minrate = 
bufsize =
nvenc_encoder_gpu =
nvenc_profile =
nvenc_preset =
nvenc_rate_control =
nvenc_temporal_aq = False
nvenc_weighted_prediction = False
nvenc_rc_lookahead =
enable_nvenc_decoder = False
enable_nvenc_hevc_decoder = False
nvenc_decoder_gpu =
nvenc_hevc_decoder_gpu =
ios-first-track-only = False
ios-audio-filter =
ios-move-last = False
max-audio-channels =
audio-codec = ac3
audio-language = eng
audio-default-language =
audio-channel-bitrate =
audio-filter =
audio-copy-original = False
subtitle-codec = mov_text
subtitle-language = eng
subtitle-default-language =
subtitle-encoding =
fullpathguess = True
convert-mp4 = False
tagfile = True
tag-language = en
download-artwork = Poster
download-subs = False
embed-subs = True
embed-only-internal-subs = False
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt =
aac_adtstoasc = False
handle_m2ts_files = False
forceconvert = False
vsync = -1
sample_rate = 
burn_in_forced_subs = True
preopts = 
postopts =-preset,ultrafast

**Comment by ethanopp** [comment]
Seems that this was an issue with using apt-get ffmpeg because it pulls an older version where the 'max_muxing_queue_size' option was not yet introduced.

Updating to pull ffmpeg 3.4.1 fixed this
