### ISSUE TITLE
Crash on manual process

### ISSUE THREAD

**Issue by pascaldulieu** [Collisionc/sickbeard_mp4_automator#14]
When running the manual script i get this error. I'm not sure if its just for MKV's.

Running on Python 2.7.15rc1
```
Traceback (most recent call last):
  File "manual.py", line 416, in <module>
    main()
  File "manual.py", line 407, in main
    processFile(path, tagdata)
  File "manual.py", line 218, in processFile
    output = converter.process(inputfile, True)
  File "/home/user/animemp4/mkvtomp4.py", line 266, in process
    options = self.generateOptions(inputfile, original=original)
  File "/home/user/animemp4/mkvtomp4.py", line 673, in generateOptions
    if s.metadata['language'].lower() not in self.swl:
TypeError: argument of type 'NoneType' is not iterable
```

Works without issues with mdhiggins version. but no way to burn the subtitles there.

**Comment by pascaldulieu** [comment]
Got a little further this time. Still crashing tho

```
[          ] 0%Error converting file, FFMPEG error.
Traceback (most recent call last):
  File "/home/user/animemp4/mkvtomp4.py", line 1040, in convert
    for timecode in conv:
  File "/home/user/animemp4/converter/__init__.py", line 243, in convert
    timeout=timeout, preopts=preopts, postopts=postopts):
  File "/home/user/animemp4/converter/ffmpeg.py", line 631, in convert
    line, pid=p.pid)
FFMpegConvertError: <FFMpegConvertError error="Conversion failed!", pid=18705, cmd="/usr/bin/ffmpeg -fix_sub_duration -vsync -1 -i /mnt/media/Anime/My Hero Academia/Season 3/My Hero Academia - S03E18 - Rush!.mkv -vcodec libx264 -map 0:0 -pix_fmt yuv420p -vb 6101k -c:a:0 copy -map 0:1 -metadata:s:a:0 language=jpn -disposition:a:0 default -vf subtitles='\:/mnt/media/Anime/My Hero Academia/Season 3\\My Hero Academia - S03E18 - Rush!.mkv:si=0' -f mp4 -threads 0 -max_muxing_queue_size 2048 -movflags faststart -y /mnt/media/Anime/My Hero Academia/Season 3/My Hero Academia - S03E18 - Rush!.mp4">
/usr/bin/ffmpeg -fix_sub_duration -vsync -1 -i /mnt/media/Anime/My Hero Academia/Season 3/My Hero Academia - S03E18 - Rush!.mkv -vcodec libx264 -map 0:0 -pix_fmt yuv420p -vb 6101k -c:a:0 copy -map 0:1 -metadata:s:a:0 language=jpn -disposition:a:0 default -vf subtitles='\:/mnt/media/Anime/My Hero Academia/Season 3\\My Hero Academia - S03E18 - Rush!.mkv:si=0' -f mp4 -threads 0 -max_muxing_queue_size 2048 -movflags faststart -y /mnt/media/Anime/My Hero Academia/Season 3/My Hero Academia - S03E18 - Rush!.mp4
ffmpeg version 3.4.4-0ubuntu0.18.04.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
  configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Input #0, matroska,webm, from '/mnt/media/Anime/My Hero Academia/Season 3/My Hero Academia - S03E18 - Rush!.mkv':
  Metadata:
    encoder         : no_variable_data
    creation_time   : 1970-01-01T00:00:00.000000Z
  Duration: 00:23:41.81, start: 0.000000, bitrate: 6101 kb/s
    Stream #0:0: Video: h264 (High), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Metadata:
      BPS             : 5998459
      BPS-eng         : 5998459
      DURATION        : 00:23:35.082000000
      DURATION-eng    : 00:23:35.082000000
      NUMBER_OF_FRAMES: 33928
      NUMBER_OF_FRAMES-eng: 33928
      NUMBER_OF_BYTES : 1061039044
      NUMBER_OF_BYTES-eng: 1061039044
      _STATISTICS_WRITING_APP: no_variable_data
      _STATISTICS_WRITING_APP-eng: no_variable_data
      _STATISTICS_WRITING_DATE_UTC: 1970-01-01 00:00:00
      _STATISTICS_WRITING_DATE_UTC-eng: 1970-01-01 00:00:00
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:1(jpn): Audio: aac (LC), 44100 Hz, stereo, fltp (default)
    Metadata:
      BPS             : 128000
      BPS-eng         : 128000
      DURATION        : 00:23:35.140000000
      DURATION-eng    : 00:23:35.140000000
      NUMBER_OF_FRAMES: 60945
      NUMBER_OF_FRAMES-eng: 60945
      NUMBER_OF_BYTES : 22642243
      NUMBER_OF_BYTES-eng: 22642243
      _STATISTICS_WRITING_APP: no_variable_data
      _STATISTICS_WRITING_APP-eng: no_variable_data
      _STATISTICS_WRITING_DATE_UTC: 1970-01-01 00:00:00
      _STATISTICS_WRITING_DATE_UTC-eng: 1970-01-01 00:00:00
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:2(eng): Subtitle: ass (default)
    Metadata:
      BPS             : 160
      BPS-eng         : 160
      DURATION        : 00:23:40.080000000
      DURATION-eng    : 00:23:40.080000000
      NUMBER_OF_FRAMES: 422
      NUMBER_OF_FRAMES-eng: 422
      NUMBER_OF_BYTES : 28461
      NUMBER_OF_BYTES-eng: 28461
      _STATISTICS_WRITING_APP: no_variable_data
      _STATISTICS_WRITING_APP-eng: no_variable_data
      _STATISTICS_WRITING_DATE_UTC: 1970-01-01 00:00:00
      _STATISTICS_WRITING_DATE_UTC-eng: 1970-01-01 00:00:00
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:3: Attachment: ttf
    Metadata:
      filename        : OpenSans-Semibold.ttf
      mimetype        : application/x-truetype-font
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[Parsed_subtitles_0 @ 0x56142bab2e20] Shaper: FriBidi 0.19.7 (SIMPLE) HarfBuzz-ng 1.7.2 (COMPLEX)
[Parsed_subtitles_0 @ 0x56142bab2e20] Unable to open :/mnt/media/Anime/My Hero Academia/Season 3\My Hero Academia - S03E18 - Rush!.mkv
[AVFilterGraph @ 0x56142bb77840] Error initializing filter 'subtitles' with args '\:/mnt/media/Anime/My Hero Academia/Season 3\\My Hero Academia - S03E18 - Rush!.mkv:si=0'
Error reinitializing filters!
Failed to inject frame into filter network: Protocol not found
Error while processing the decoded data for stream #0:0
Conversion failed!
```

**Comment by Collisionc** [comment]
Ah, ok. That's a file path issue because I never tested the script on linux... I'll get it working tonight.

**Comment by Collisionc** [comment]
Yeah, I even included a comment in the code forever ago saying that it probably wouldn't work on non-windows computers, see if it works any better now.

**Comment by pascaldulieu** [comment]
Still crashing after latest pull
```
Traceback (most recent call last):
  File "manual.py", line 416, in <module>
    main()
  File "manual.py", line 407, in main
    processFile(path, tagdata)
  File "manual.py", line 218, in processFile
    output = converter.process(inputfile, True)
  File "/home/user/animemp4/mkvtomp4.py", line 279, in process
    outputfile, inputfile = self.convert(inputfile, options, reportProgress)
  File "/home/user/animemp4/mkvtomp4.py", line 1043, in convert
    for timecode in conv:
  File "/home/user/animemp4/converter/__init__.py", line 241, in convert
    optlist = self.parse_options(options, twopass)
  File "/home/user/animemp4/converter/__init__.py", line 126, in parse_options
    raise ConverterError('Invalid subtitle codec specification')
converter.ConverterError: Invalid subtitle codec specification
```

**Comment by pascaldulieu** [comment]
I've tried eng and nothing

**Comment by pascaldulieu** [comment]
ah sorry, i misread the question. For the subtitle-codec i am using mov_text which is the default i believe

**Comment by Collisionc** [comment]
Actually you might have to set subtitle-codec=ass,srt,ssa

**Comment by pascaldulieu** [comment]
Set the codec as ass,srt,ssa and still crashing with the exact same crash.

**Comment by Collisionc** [comment]
Can you post the contents of your autoprocess.ini file ? Just the part under [MP4]

**Comment by pascaldulieu** [comment]
```
[MP4]
audio-copy-original = False
burn_in_forced_subs = True
preopts =
ffprobe = ffprobe
minrate =
nvenc_preset =
qmin =
enable_dxva2_gpu_decode = False
embed-subs = True
bufsize =
audio-codec = aac
pix-fmt =
subtitle-encoding =
download-subs = False
audio-filter =
relocate_moov = True
video-crf =
h264-max-level =
fullpathguess = True
enable_nvenc_hevc_decoder = False
download-artwork = poster
ios-move-last = False
audio-default-language =
output_extension = mp4
vsync = -1
nvenc_decoder_gpu =
video-max-width =
nvenc_rate_control =
maxrate =
ios-audio-filter =
copy_to =
nvenc_hevc_decoder_gpu =
subtitle-codec = ass, srt, ssa
video-profile =
tag-language = en
forceconvert = False
delete_original = True
audio-language =
use-hevc-qsv-decoder = False
output_format = mp4
use-qsv-decoder-with-encoder = True
enable_nvenc_decoder = False
move_to =
output_directory =
postopts =
handle_m2ts_files = False
nvenc_temporal_aq = False
threads = 0
ios-first-track-only = False
max-audio-channels =
nvenc_encoder_gpu =
subtitle-default-language =
audio-first-track-of-language = False
video-bitrate =
resolution-bitrate-restriction =
tagfile = True
ffmpeg = ffmpeg
embed-only-internal-subs = False
nvenc_rc_lookahead =
sub-providers = addic7ed, podnapisi, thesubdb, opensubtitles
post-process = False
convert-mp4 = False
qmax =
nvenc_weighted_prediction = False
nvenc_profile =
sample_rate =
ios-audio = True
audio-channel-bitrate = 256
permissions = 777
aac_adtstoasc = False
global_quality =
subtitle-language = eng
video-codec = h264, x264
```

**Comment by Collisionc** [comment]
Ok, managed to reproduce it on linux, doesn't seem to affect windows whatsoever... still not sure why it's happening, but i'll figure it out.

**Comment by Collisionc** [comment]
Whoops, didn't modify the correct option.... it seems to work now on linux. 

Also, you can change subtitle-codec back to mov_text
