### ISSUE TITLE
[Question] Nvidia Settings

### ISSUE THREAD

**Issue by justinglock40** [Collisionc/sickbeard_mp4_automator#8]
What settings do you have set for the nvidia settings in your autoProcess.ini?

**Comment by justinglock40** [comment]
Fails on automated run:

2018-02-18 20:46:55 - SonarrPostConversion - INFO - Sonarr extra script post processing started.
2018-02-18 20:46:55 - readSettings - INFO - C:\Python27\python.exe
2018-02-18 20:46:55 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
2018-02-18 20:46:55 - readSettings - WARNING - Sample rate was invalid, defaulting to 48000 KHz.
2018-02-18 20:46:55 - SonarrPostConversion - INFO - Processing G:\Plex\TV Shows\Homeland\Season 7\Homeland - S07E02 WEBDL-720p.mkv.
2018-02-18 20:46:55 - mkvtomp4 - INFO - Reading video stream.
2018-02-18 20:46:55 - mkvtomp4 - INFO - Video codec detected: h264.
2018-02-18 20:46:55 - mkvtomp4 - INFO - Pix Fmt: yuv420p.
2018-02-18 20:46:55 - mkvtomp4 - INFO - Reading audio streams.
2018-02-18 20:46:55 - mkvtomp4 - INFO - Audio detected for stream #1: eac3 [und].
2018-02-18 20:46:55 - mkvtomp4 - INFO - Creating audio stream 0 from source audio stream 1 [iOS-audio].
2018-02-18 20:46:55 - mkvtomp4 - INFO - Audio track is number 0 setting disposition to default
2018-02-18 20:46:55 - mkvtomp4 - INFO - Creating audio stream 1 from source stream 1.
2018-02-18 20:46:55 - mkvtomp4 - INFO - Audio Track is number 1 setting disposition to none
2018-02-18 20:46:55 - mkvtomp4 - INFO - Adding copy of original audio track in format eac3
2018-02-18 20:46:55 - mkvtomp4 - INFO - Reading subtitle streams.
2018-02-18 20:46:55 - mkvtomp4 - INFO - Subtitle detected for stream #2: ass [und].
2018-02-18 20:46:55 - mkvtomp4 - INFO - Ripping eng subtitle from source stream 2 into external file.
2018-02-18 20:46:56 - mkvtomp4 - INFO - G:\Plex\TV Shows\Homeland\Season 7\Homeland - S07E02 WEBDL-720p.eng.srt created.
2018-02-18 20:46:56 - mkvtomp4 - INFO - Starting conversion.
2018-02-18 20:46:56 - mkvtomp4 - ERROR - Error converting file, FFMPEG error.
Traceback (most recent call last):
  File "C:\Sickbeard\mkvtomp4.py", line 966, in convert
    for timecode in conv:
  File "C:\Sickbeard\converter\__init__.py", line 243, in convert
    timeout=timeout, preopts=preopts, postopts=postopts):
  File "C:\Sickbeard\converter\ffmpeg.py", line 632, in convert
    total_output, pid=p.pid)
FFMpegConvertError: <FFMpegConvertError error="Exited with code 1", pid=13964, cmd="C:\ffmpeg\bin\ffmpeg.exe -fix_sub_duration -vsync -1 -hwaccel dxva2 -i G:\Plex\TV Shows\Homeland\Season 7\Homeland - S07E02 WEBDL-720p.mkv -vcodec h264_nvenc -qmin 17 -maxrate 25000k -bufsize 40000k -map 0:0 -pix_fmt nv12 -vb 4000k -profile:v 2 -rc vbr_hq -gpu 0 -temporal-aq 1 -rc-lookahead 32 -level 4.1 -c:a:0 aac -map 0:1 -disposition:a:0 default -ac:a:0 2 -b:a:0 256k -ar:a:0 48000 -metadata:s:a:0 language=eng -strict experimental -c:a:1 aac -map 0:1 -disposition:a:1 none -ac:a:1 6 -b:a:1 1536k -ar:a:1 48000 -metadata:s:a:1 language=eng -strict experimental -c:a:2 copy -map 0:1 -metadata:s:a:2 language=eng -disposition:a:2 none -f mp4 -threads 0 -max_muxing_queue_size 2048 -movflags faststart -y G:\Plex\TV Shows\Homeland\Season 7\Homeland - S07E02 WEBDL-720p.mp4">
2018-02-18 20:46:56 - mkvtomp4 - ERROR - C:\ffmpeg\bin\ffmpeg.exe -fix_sub_duration -vsync -1 -hwaccel dxva2 -i G:\Plex\TV Shows\Homeland\Season 7\Homeland - S07E02 WEBDL-720p.mkv -vcodec h264_nvenc -qmin 17 -maxrate 25000k -bufsize 40000k -map 0:0 -pix_fmt nv12 -vb 4000k -profile:v 2 -rc vbr_hq -gpu 0 -temporal-aq 1 -rc-lookahead 32 -level 4.1 -c:a:0 aac -map 0:1 -disposition:a:0 default -ac:a:0 2 -b:a:0 256k -ar:a:0 48000 -metadata:s:a:0 language=eng -strict experimental -c:a:1 aac -map 0:1 -disposition:a:1 none -ac:a:1 6 -b:a:1 1536k -ar:a:1 48000 -metadata:s:a:1 language=eng -strict experimental -c:a:2 copy -map 0:1 -metadata:s:a:2 language=eng -disposition:a:2 none -f mp4 -threads 0 -max_muxing_queue_size 2048 -movflags faststart -y G:\Plex\TV Shows\Homeland\Season 7\Homeland - S07E02 WEBDL-720p.mp4
2018-02-18 20:46:56 - mkvtomp4 - ERROR - ffmpeg version N-89861-g78e884f3fb Copyright (c) 2000-2018 the FFmpeg developers

  built with gcc 7.2.0 (GCC)

  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libmfx --enable-amf --enable-cuda --enable-cuvid --enable-d3d11va --enable-nvenc --enable-dxva2 --enable-avisynth

  libavutil      56.  7.100 / 56.  7.100

  libavcodec     58.  9.100 / 58.  9.100

  libavformat    58.  5.100 / 58.  5.100

  libavdevice    58.  0.101 / 58.  0.101

  libavfilter     7. 11.101 /  7. 11.101

  libswscale      5.  0.101 /  5.  0.101

  libswresample   3.  0.101 /  3.  0.101

  libpostproc    55.  0.100 / 55.  0.100

Input #0, matroska,webm, from 'G:\Plex\TV Shows\Homeland\Season 7\Homeland - S07E02 WEBDL-720p.mkv':

  Metadata:

    ENCODER         : Lavf57.82.100

  Duration: 00:56:09.20, start: 0.000000, bitrate: 3769 kb/s

    Chapter #0:0: start 0.000000, end 4.000000

    Chapter #0:1: start 4.000000, end 92.000000

    Chapter #0:2: start 92.000000, end 178.000000

    Chapter #0:3: start 178.000000, end 435.000000

    Chapter #0:4: start 435.000000, end 548.000000

    Chapter #0:5: start 548.000000, end 727.000000

    Chapter #0:6: start 727.000000, end 836.000000

    Chapter #0:7: start 836.000000, end 1101.000000

    Chapter #0:8: start 1101.000000, end 1320.000000

    Chapter #0:9: start 1320.000000, end 1498.000000

    Chapter #0:10: start 1498.000000, end 1673.000000

    Chapter #0:11: start 1673.000000, end 1759.000000

    Chapter #0:12: start 1759.000000, end 1916.000000

    Chapter #0:13: start 1916.000000, end 2083.000000

    Chapter #0:14: start 2083.000000, end 2412.000000

    Chapter #0:15: start 2412.000000, end 2533.000000

    Chapter #0:16: start 2533.000000, end 2662.000000

    Chapter #0:17: start 2662.000000, end 2789.000000

    Chapter #0:18: start 2789.000000, end 2909.000000

    Chapter #0:19: start 2909.000000, end 3308.000000

    Chapter #0:20: start 3308.000000, end 3327.000000

    Chapter #0:21: start 3327.000000, end 3369.199000

    Stream #0:0: Video: h264 (High), yuv420p(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)

    Metadata:

      DURATION        : 00:56:09.198000000

    Stream #0:1: Audio: eac3, 48000 Hz, 5.1(side), fltp, 640 kb/s (default)

    Metadata:

      DURATION        : 00:56:09.152000000

    Stream #0:2: Subtitle: ass

    Metadata:

      ENCODER         : Lavc57.106.101 ssa

      DURATION        : 00:55:17.667000000

[AVHWDeviceContext @ 00000236d8b41e00] Failed to create Direct3D device

Device creation failed: -1313558101.

[h264 @ 00000236d8b45b40] No device available for decoder: device type dxva2 needed for codec h264.

Stream mapping:

  Stream #0:0 -> #0:0 (h264 (native) -> h264 (h264_nvenc))

  Stream #0:1 -> #0:1 (eac3 (native) -> aac (native))

  Stream #0:1 -> #0:2 (eac3 (native) -> aac (native))

  Stream #0:1 -> #0:3 (copy)

Device setup failed for decoder on input stream #0:0 : Unknown error occurred


2018-02-18 20:46:56 - mkvtomp4 - ERROR - G:\Plex\TV Shows\Homeland\Season 7\Homeland - S07E02 WEBDL-720p.mp4 deleted.

**Comment by justinglock40** [comment]
Passes on manual run:
2018-02-18 20:50:42 - MANUAL - INFO - Manual processor started.
2018-02-18 20:50:42 - MANUAL - INFO - C:\Python27\python.exe
2018-02-18 20:50:42 - MANUAL - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
2018-02-18 20:50:42 - MANUAL - WARNING - Sample rate was invalid, defaulting to 48000 KHz.
2018-02-18 20:50:42 - MANUAL - DEBUG - Settings imported.
2018-02-18 20:50:42 - MANUAL - DEBUG - G:\Complete\The Death of Stalin 2017 1080p WEB-DL DD5.1 H264-CMRG\The Death of Stalin 2017 1080p WEB-DL DD5.1 H264-CMRG.mkv is valid.
2018-02-18 20:50:43 - MANUAL - DEBUG - Settings imported.
2018-02-18 20:50:43 - MANUAL - DEBUG - G:\Complete\The Death of Stalin 2017 1080p WEB-DL DD5.1 H264-CMRG\The Death of Stalin 2017 1080p WEB-DL DD5.1 H264-CMRG.mkv is valid.
2018-02-18 20:50:43 - MANUAL - DEBUG - Settings imported.
2018-02-18 20:50:43 - MANUAL - DEBUG - Process started.
2018-02-18 20:50:43 - MANUAL - DEBUG - G:\Complete\The Death of Stalin 2017 1080p WEB-DL DD5.1 H264-CMRG\The Death of Stalin 2017 1080p WEB-DL DD5.1 H264-CMRG.mkv is valid.
2018-02-18 20:50:43 - MANUAL - DEBUG - G:\Complete\The Death of Stalin 2017 1080p WEB-DL DD5.1 H264-CMRG\The Death of Stalin 2017 1080p WEB-DL DD5.1 H264-CMRG.mkv needs processing.
2018-02-18 20:50:43 - MANUAL - INFO - Reading video stream.
2018-02-18 20:50:43 - MANUAL - INFO - Video codec detected: h264.
2018-02-18 20:50:43 - MANUAL - DEBUG - Total bitrate is 5608195.0.
2018-02-18 20:50:43 - MANUAL - DEBUG - Total audio bitrate is 384000.
2018-02-18 20:50:43 - MANUAL - DEBUG - Estimated video bitrate is 5224195.0.
2018-02-18 20:50:43 - MANUAL - INFO - Pix Fmt: yuv420p.
2018-02-18 20:50:43 - MANUAL - DEBUG - Video codec: nvenc_h264.
2018-02-18 20:50:43 - MANUAL - DEBUG - Video bitrate: 8000.
2018-02-18 20:50:43 - MANUAL - INFO - Reading audio streams.
2018-02-18 20:50:43 - MANUAL - INFO - Audio detected for stream #0: ac3 [eng].
2018-02-18 20:50:43 - MANUAL - INFO - Creating audio stream 0 from source audio stream 0 [iOS-audio].
2018-02-18 20:50:43 - MANUAL - DEBUG - Audio codec: aac.
2018-02-18 20:50:43 - MANUAL - DEBUG - Channels: 2.
2018-02-18 20:50:43 - MANUAL - DEBUG - Filter: None.
2018-02-18 20:50:43 - MANUAL - DEBUG - Bitrate: 256.
2018-02-18 20:50:43 - MANUAL - DEBUG - Language: eng.
2018-02-18 20:50:43 - MANUAL - INFO - Audio track is number 0 setting disposition to default
2018-02-18 20:50:43 - MANUAL - INFO - Creating audio stream 1 from source stream 0.
2018-02-18 20:50:43 - MANUAL - DEBUG - Audio codec: copy.
2018-02-18 20:50:43 - MANUAL - DEBUG - Channels: 6.
2018-02-18 20:50:43 - MANUAL - DEBUG - Bitrate: 1536.
2018-02-18 20:50:43 - MANUAL - DEBUG - Language: eng
2018-02-18 20:50:43 - MANUAL - DEBUG - Filter: None
2018-02-18 20:50:43 - MANUAL - DEBUG - Not creating any additional iOS audio streams.
2018-02-18 20:50:43 - MANUAL - INFO - Audio Track is number 0 setting disposition to none
2018-02-18 20:50:43 - MANUAL - INFO - Reading subtitle streams.
2018-02-18 20:50:43 - MANUAL - INFO - {
    "preopts": [
        "-fix_sub_duration", 
        "-vsync", 
        "-1", 
        "-hwaccel", 
        "dxva2"
    ], 
    "subtitle": {}, 
    "format": "mp4", 
    "postopts": [
        "-threads", 
        "0", 
        "-max_muxing_queue_size", 
        "2048", 
        "-movflags", 
        "faststart"
    ], 
    "video": {
        "pix_fmt": "nv12", 
        "map": 1, 
        "qmax": "", 
        "nvenc_preset": "slow", 
        "qmin": "17", 
        "bufsize": "40000", 
        "bitrate": "8000", 
        "nvenc_temporal_aq": true, 
        "nvenc_profile": "2", 
        "level": 4.1, 
        "nvenc_rc_lookahead": "32", 
        "minrate": "", 
        "nvenc_gpu": "0", 
        "codec": "nvenc_h264", 
        "vsync": "-1", 
        "nvenc_rate_control": "vbr_hq", 
        "maxrate": "25000", 
        "global_quality": ""
    }, 
    "audio": {
        "0": {
            "channels": 2, 
            "map": 0, 
            "codec": "aac", 
            "disposition": "default", 
            "language": "eng", 
            "samplerate": 48000, 
            "bitrate": 256, 
            "filter": null
        }, 
        "1": {
            "channels": 6, 
            "map": 0, 
            "codec": "copy", 
            "disposition": "none", 
            "language": "eng", 
            "samplerate": 48000, 
            "bitrate": 1536, 
            "filter": null
        }
    }
}
2018-02-18 20:50:43 - MANUAL - INFO - Starting conversion.
2018-02-18 20:50:43 - MANUAL - DEBUG - Input directory: G:\Complete\The Death of Stalin 2017 1080p WEB-DL DD5.1 H264-CMRG.
2018-02-18 20:50:43 - MANUAL - DEBUG - File name: The Death of Stalin 2017 1080p WEB-DL DD5.1 H264-CMRG.
2018-02-18 20:50:43 - MANUAL - DEBUG - Input extension: mkv.
2018-02-18 20:50:43 - MANUAL - DEBUG - Output directory: G:\Complete\The Death of Stalin 2017 1080p WEB-DL DD5.1 H264-CMRG.
2018-02-18 20:50:43 - MANUAL - DEBUG - Output file: G:\Complete\The Death of Stalin 2017 1080p WEB-DL DD5.1 H264-CMRG\The Death of Stalin 2017 1080p WEB-DL DD5.1 H264-CMRG.mp4.

**Comment by justinglock40** [comment]
Any idea what's causing the automated failure?

**Comment by Collisionc** [comment]
That's a strange error, because if DXVA2 fails, it should just fallback to a normal h264 encoder.

Are you running this on windows?  What CPU/GPU?

**Comment by Collisionc** [comment]
Do you have a monitor hooked up to it? Or do you just remote in?

**Comment by justinglock40** [comment]
Remote 95% of the time. The 1050Ti is hooked up via HDMI. The iGPU has a VGA cable attached but not used ever.

**Comment by Collisionc** [comment]
Try disabling the integrated graphics in BIOS, there's some obscure issues with dxva2 that lead to this occurring that no one has been able to resolve other than hooking up a monitor and disabling integrated graphics, but it's not going to be something that I can fix. :( 

You could use nvenc decoder instead of dxva2, if you use a recent build of FFMPEG they have resolved some of the decoding issues that I was having in the past... I just haven't swapped to it because of how stable dxva2 has been.

**Comment by justinglock40** [comment]
It’s a dell motherboard so no real options. I’ve just went to using nvenc.

**Comment by justinglock40** [comment]
Have you ever encountered this? 

Stream mapping:
  Stream #0:0 -> #0:0 (hevc (hevc_cuvid) -> h264 (h264_nvenc))
  Stream #0:2 -> #0:1 (ac3 (native) -> aac (native))
  Stream #0:2 -> #0:2 (copy)
Press [q] to stop, [?] for help
[h264_nvenc @ 00000295b490d500] No NVENC capable devices found
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height

**Comment by Collisionc** [comment]
Generally that only happens when more than 2 videos are attempting to be encoded.

**Comment by justinglock40** [comment]
When you transcode does it utilize the GPU at 100%? This is what I get when transcoding a 4K @ 60mbps

<img width="435" alt="screenshot at feb 25 13-25-37" src="https://user-images.githubusercontent.com/23133649/36645504-6f08e880-1a2f-11e8-9a29-ef786a5a6276.png">

**Comment by Collisionc** [comment]
Yeah, that looks about right when you are encoding audio with video. Audio is actually the bottleneck in a lot of cases, if you have it only copy the audio it'll bump up to 100% "Video Encode" usage. However, the highest total GPU usage I've ever seen with 2 videos transcoding is around 40% on a 1080 gtx.

**Comment by justinglock40** [comment]
Do you think it would be difficult to edit this script to just convert the audio but leave mkv containers? Since most devices handle mkv now?

**Comment by Collisionc** [comment]
Pretty easy, just change the output to .mkv and add  -f matroska to the line.

**Comment by justinglock40** [comment]
Do I do that in the autoProcess.ini?

**Comment by Collisionc** [comment]
No, I'd have to add an option, i'll do that sometime today.

**Comment by Collisionc** [comment]
Ok, maybe not sometime today, it's a bit more complex than that... some subtitle formats that mp4 supports, mkv doesn't. Should be doable, just more than a days work.

**Comment by Collisionc** [comment]
I'm still working on this slowly, I'm having to throw a lot of files at it to catch all the subtle differences between mkv/mp4.

**Comment by justinglock40** [comment]
Ok take your time

**Comment by justinglock40** [comment]
Do you know why some videos trigger this happens on Roku, Fire Stick and Tivo?
Sometimes it Direct Plays but sometimes it transcodes the mp4 to mpegts

**Comment by justinglock40** [comment]
![img_0052](https://user-images.githubusercontent.com/23133649/38223712-d5666c8a-36b1-11e8-9c8d-50251c672fe7.PNG)

**Comment by justinglock40** [comment]
![img_0052](https://user-images.githubusercontent.com/23133649/38223732-f429eff2-36b1-11e8-86a8-756d27b42d79.jpg)

**Comment by Collisionc** [comment]
I've noticed recently that Plex is using MPEGTS as the container of choice when transcoding files due to bitrate/resolution restrictions.  I can't say for sure, but this is probably a change that they intentionally made. It should still direct play files when bitrate/resolution do not need to be changed, so if you are seeing transcodes try increasing the bandwidth on that player as it might be set to the 3 megabit default.

It doesn't particularly matter what container is used, converting on the fly from mp4 to mkv or mpegts takes maybe 1-2 seconds at most.

**Comment by Collisionc** [comment]
Ok, just change output_extension and output_format to mkv and it should work fine now.  Let me know if you run into any issues.
